import 'App/Routes/PessoasRoutes'
import 'App/Routes/ClientesRoutes'
import 'App/Routes/AtendimentosRoutes'
import 'App/Routes/EnderecosRoutes'
import 'App/Routes/TipoCorteCabelos'
import 'App/Routes/TipoUsuariosRoutes'
import 'App/Routes/UsuariosRoutes'
